// <auto-generated />
using System;
using CityInfo2.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CityInfo2.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20210512162254_SampleData")]
    partial class SampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityInfo2.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new { Id = 1, Description = "A very buzzling city of the USA", Name = "New York City" },
                        new { Id = 2, Description = "A very buzzling city of Nigeria", Name = "Lagos" },
                        new { Id = 3, Description = "A very buzzling city of the French", Name = "Paris" }
                    );
                });

            modelBuilder.Entity("CityInfo2.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new { Id = 1, CityId = 1, Description = "The beautiful greenery park", Name = "Central Park" },
                        new { Id = 2, CityId = 1, Description = "The 102-storey sky scrapper", Name = "Empire State Building" },
                        new { Id = 3, CityId = 2, Description = "The beautiful greenery park", Name = "JJT Park" },
                        new { Id = 4, CityId = 2, Description = "The beautiful new well designed and planned City on the Ocean", Name = "Eko Antlantic city" },
                        new { Id = 5, CityId = 3, Description = "The beautiful greenery park", Name = "Central Park" },
                        new { Id = 6, CityId = 3, Description = "The High rise iconic portrait of Paris", Name = "Eiffel Tower" }
                    );
                });

            modelBuilder.Entity("CityInfo2.API.Models.PointsOfInterestDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterestDto");
                });

            modelBuilder.Entity("CityInfo2.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo2.API.Entities.City", "city")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CityInfo2.API.Models.PointsOfInterestDto", b =>
                {
                    b.HasOne("CityInfo2.API.Entities.City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId");
                });
#pragma warning restore 612, 618
        }
    }
}
